### ISSUE TITLE
The site is unavailable

### ISSUE THREAD

**Issue by FoggyFinder** [amazingant/FSharpWpfGuide#1]
At the moment the site is not available. The article was very useful, is there a possibility to restore it? Maybe even in the form of a git book?
![1](https://cloud.githubusercontent.com/assets/16510738/17511873/0ea85252-5e36-11e6-95fb-6ce61bc19516.jpg)

**Comment by FoggyFinder** [comment]
Update. I found: https://github.com/amazingant/amazingant.com/blob/master/content/2014-12-18-FSharp-and-WPF.md

**Comment by amazingant** [comment]
Not sure if you poked around the site at all, but as the 404 page mentioned, there was a recent migration about two months ago; the new page is [here](https://amazingant.com/blog/2014/12/08/FSharp-and-WPF/). You are welcome to read through it on GitHub as well, but I'm sure you can understand that the source code for the site was not _strictly_ intended to be reading material. 😉

**Comment by FoggyFinder** [comment]
Great, thanks.

Do you have no plans to write a full git-book on working with WPF in F#?

**Comment by amazingant** [comment]
You are welcome to do so if you want to, as the source code here is under the [MIT license](https://github.com/amazingant/FSharpWpfGuide/blob/master/LICENSE) and my website content is under the [Creative Commons BY-NC-SA](https://github.com/amazingant/amazingant.com/blob/master/LICENSE) license. I'm not sure what a git-book is, but I have no plans to work on one.
